"""initial schema - 13 tables

Revision ID: 304cd6261f7a
Revises: 
Create Date: 2026-04-02 13:00:38.892511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '304cd6261f7a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_windows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('window_name', sa.String(length=100), nullable=False),
    sa.Column('start_hour', sa.Integer(), nullable=False),
    sa.Column('end_hour', sa.Integer(), nullable=False),
    sa.Column('days_of_week', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment_targets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('linkedin_url', sa.String(length=500), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('last_comment_date', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('template_text', sa.Text(), nullable=False),
    sa.Column('tone', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('safety_flag', sa.Integer(), nullable=False),
    sa.Column('example_use', sa.Text(), nullable=False),
    sa.Column('persona', sa.String(length=100), nullable=False),
    sa.Column('use_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_templates_persona'), 'comment_templates', ['persona'], unique=False)
    op.create_table('content_bank',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('post_type', sa.String(length=30), nullable=False),
    sa.Column('draft', sa.Text(), nullable=False),
    sa.Column('safety_flag', sa.Integer(), nullable=False),
    sa.Column('ready', sa.Boolean(), nullable=False),
    sa.Column('last_used', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_bank_category'), 'content_bank', ['category'], unique=False)
    op.create_table('engine_control',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('phase', sa.String(length=20), nullable=False),
    sa.Column('main_user_posting', sa.Boolean(), nullable=False),
    sa.Column('phantom_engagement', sa.Boolean(), nullable=False),
    sa.Column('commenting', sa.Boolean(), nullable=False),
    sa.Column('replying', sa.Boolean(), nullable=False),
    sa.Column('last_run', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feed_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('feed_type', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_fetched', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outbound_queue',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('post_id', sa.String(length=100), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('persona', sa.String(length=100), nullable=False),
    sa.Column('target_name', sa.String(length=200), nullable=False),
    sa.Column('target_url', sa.String(length=500), nullable=True),
    sa.Column('draft_text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('scheduled_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbound_queue_status'), 'outbound_queue', ['status'], unique=False)
    op.create_index('ix_outbound_queue_status_created', 'outbound_queue', ['status', 'created_at'], unique=False)
    op.create_table('pipeline_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trigger_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('phase', sa.String(length=20), nullable=False),
    sa.Column('posts_made', sa.Integer(), nullable=False),
    sa.Column('comments_made', sa.Integer(), nullable=False),
    sa.Column('replies_made', sa.Integer(), nullable=False),
    sa.Column('phantom_actions', sa.Integer(), nullable=False),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reply_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('condition_type', sa.String(length=30), nullable=False),
    sa.Column('trigger', sa.String(length=500), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repost_bank',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_name', sa.String(length=200), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('commentary_prompt', sa.Text(), nullable=False),
    sa.Column('safety_flag', sa.Integer(), nullable=False),
    sa.Column('last_used', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('safety_terms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('term', sa.String(length=200), nullable=False),
    sa.Column('response', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('term')
    )
    op.create_table('schedule_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phase', sa.String(length=30), nullable=False),
    sa.Column('posts_per_week', sa.Integer(), nullable=False),
    sa.Column('comments_per_day_min', sa.Integer(), nullable=False),
    sa.Column('comments_per_day_max', sa.Integer(), nullable=False),
    sa.Column('phantom_comments_min', sa.Integer(), nullable=False),
    sa.Column('phantom_comments_max', sa.Integer(), nullable=False),
    sa.Column('min_delay_sec', sa.Integer(), nullable=False),
    sa.Column('max_likes_per_day', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phase')
    )
    op.create_table('system_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('module', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target', sa.String(length=500), nullable=False),
    sa.Column('result', sa.String(length=50), nullable=False),
    sa.Column('safety', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_logs_action'), 'system_logs', ['action'], unique=False)
    op.create_index(op.f('ix_system_logs_module'), 'system_logs', ['module'], unique=False)
    op.create_index(op.f('ix_system_logs_timestamp'), 'system_logs', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_logs_timestamp'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_module'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_action'), table_name='system_logs')
    op.drop_table('system_logs')
    op.drop_table('schedule_configs')
    op.drop_table('safety_terms')
    op.drop_table('repost_bank')
    op.drop_table('reply_rules')
    op.drop_table('pipeline_runs')
    op.drop_index('ix_outbound_queue_status_created', table_name='outbound_queue')
    op.drop_index(op.f('ix_outbound_queue_status'), table_name='outbound_queue')
    op.drop_table('outbound_queue')
    op.drop_table('feed_sources')
    op.drop_table('engine_control')
    op.drop_index(op.f('ix_content_bank_category'), table_name='content_bank')
    op.drop_table('content_bank')
    op.drop_index(op.f('ix_comment_templates_persona'), table_name='comment_templates')
    op.drop_table('comment_templates')
    op.drop_table('comment_targets')
    op.drop_table('activity_windows')
    # ### end Alembic commands ###
